"""add_schedule_configs_table

Revision ID: 0930c0dc24b8
Revises: 690a24f5ce3f
Create Date: 2025-10-15 18:19:29.122993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0930c0dc24b8'
down_revision = '690a24f5ce3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publication_queue_post_id_fkey', 'publication_queue', type_='foreignkey')
    op.drop_constraint('publication_queue_feed_id_fkey', 'publication_queue', type_='foreignkey')
    op.create_foreign_key(None, 'publication_queue', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'publication_queue', 'feeds', ['feed_id'], ['id'])
    op.drop_column('publication_queue', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_queue', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publication_queue', type_='foreignkey')
    op.drop_constraint(None, 'publication_queue', type_='foreignkey')
    op.create_foreign_key('publication_queue_feed_id_fkey', 'publication_queue', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('publication_queue_post_id_fkey', 'publication_queue', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###



