"""Add extra_data field to Publication model

Revision ID: 2f0fe8c89379
Revises: e59e5b4094a3
Create Date: 2025-10-27 09:19:36.415256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0fe8c89379'
down_revision = '86f346ee8d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'extra_data')
    # ### end Alembic commands ###



