"""Add network_prompts column to feeds table

Revision ID: a544d0d64aaf
Revises: 0a07d586c10a
Create Date: 2025-09-23 00:29:49.835153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a544d0d64aaf'
down_revision = '0a07d586c10a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('network_prompts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'network_prompts')
    # ### end Alembic commands ###
