"""Add schedule_configs table

Revision ID: e59e5b4094a3
Revises: 0930c0dc24b8
Create Date: 2025-10-16 23:07:48.940550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e59e5b4094a3'
down_revision = '0930c0dc24b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('network', sa.VARCHAR(length=50), nullable=False),
    sa.Column('day_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('max_posts_per_day', sa.INTEGER(), nullable=True),
    sa.Column('specific_days', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='schedule_configs_pkey')
    )
    op.create_index('ix_schedule_configs_id', 'schedule_configs', ['id'], unique=False)
    op.create_index('ix_schedule_configs_network', 'schedule_configs', ['network'], unique=False)
    op.create_index('ix_schedule_configs_day_type', 'schedule_configs', ['day_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_configs_day_type', table_name='schedule_configs')
    op.drop_index('ix_schedule_configs_network', table_name='schedule_configs')
    op.drop_index('ix_schedule_configs_id', table_name='schedule_configs')
    op.drop_table('schedule_configs')
    # ### end Alembic commands ###



